module.exports = {
  aquatic10: {
    isAquaticLevel: true,
    ocean: 'warm',
    groundPlane: ["sand", "sand", "prismarine", "darkPrismarine", "prismarine", "prismarine", "darkPrismarine", "prismarine", "sand", "sand", "sand", "seaLantern", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "seaLantern", "sand", "prismarine", "prismarine", "prismarine", "darkPrismarine", "darkPrismarine", "darkPrismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "seaLantern", "redCoralBlock", "darkPrismarine", "darkPrismarine", "prismarine", "prismarine", "sand", "sand", "prismarine", "prismarine", "darkPrismarine", "darkPrismarine", "darkPrismarine", "prismarine", "prismarine", "prismarine", "prismarine", "sand", "prismarine", "prismarine", "seaLantern", "darkPrismarine", "darkPrismarine", "blueCoralBlock", "darkPrismarine", "seaLantern", "prismarine", "sand", "prismarine", "prismarine", "darkPrismarine", "darkPrismarine", "darkPrismarine", "darkPrismarine", "darkPrismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "darkPrismarine", "darkPrismarine", "darkPrismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "prismarine", "redCoralBlock", "sand", "redCoralBlock", "prismarine", "prismarine", "sand", "sand", "prismarine", "prismarine", "prismarine", "sand", "sand", "blueCoralBlock", "sand", "sand", "sand"],
    groundDecorationPlane: ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    actionPlane: ["", "", "prismarine", "darkPrismarine", "prismarine", "prismarine", "darkPrismarine", "prismarine", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "prismarine", "", "", "prismarine", "prismarine", "prismarine", "", "", "", "", "prismarine", "", "", "", "diamondMiniblock", "prismarine", "", "", "", "", "prismarine", "", "", "prismarine", "prismarine", "prismarine", "", "darkPrismarine", "", "", "prismarine", "", "", "", "", "", "", "", "", "", "prismarine", "", "", "", "", "", "", "darkPrismarine", "", "", "prismarine", "", "", "prismarine", "", "prismarine", "prismarine", "prismarine", "", "", "prismarine", "", "", "", "", "prismarine", "prismarine", "prismarine", "", "", "prismarine", "", "", "prismarine", "", "", "", ""],
    entities: [],
    playerStartPosition: [1, 8],
    playerStartDirection: 0,
    verificationFunction: verificationAPI => verificationAPI.isEntityAt("Player", [6, 3]),
  },
};
